[project]
name = "job_controller"
readme = "README.md"
version = "0.0.1"
dependencies = [
    "confluent-kafka==2.1.0",
    "kubernetes==25.3.0",
    "psycopg2==2.9.5",
    "SQLAlchemy==2.0.7"
]

[project.urls]
"Repository" = "https://github.com/interactivereduction/jobcontroller"

[project.scripts]
jobcontroller = "job_controller.main:main"

[project.optional-dependencies]
formatting = [
    "toml==0.10.2",
    "black==23.1.0",
]

test = [
    "pytest==7.2.2",
    "mock-alchemy==0.2.6"
]

code-inspection = [
    "pylint==2.17.1",
    "mypy==1.2.0",
    "job_controller[test]"
]

[tool.setuptools]
packages = ["job_controller"]
