[project]
name = "jobcontroller"
readme = "README.md"
version = "0.0.1"
dependencies = [
    "confluent-kafka==1.9.2",
    "kubernetes==25.3.0"
]

[project.urls]
"Repository" = "https://github.com/interactivereduction/jobcontroller"

[project.scripts]
jobcontroller = "jobcontroller.jobcontroller:main"

[project.optional-dependencies]
formatting = [
    "toml==0.10.2",
    "black==0.32.0",
]

test = [
    "pytest==7.2.0"
]

code-inspection = [
    "pylint==2.15.7",
    "mypy==0.991",
    "jobcontroller[test]"
]

[tool.setuptools]
packages = ["jobcontroller"]
