---
on:
  push:

jobs:
  e2e:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v2

    - name: Create archive-like folder
      run: |
        mkdir -p /archive/NDXMARI/Instrument/data/cycle_22_5/
        touch /archive/NDXMARI/Instrument/data/cycle_22_5/MAR28503.nxs

    - name: Create ceph-like folder
      run: |
        mkdir -p /ceph/MARI/RBNumber/RB0/autoreduced

    - name: Start minikube
      uses: medyagh/setup-minikube@master

    - name: Clone k8s repo
      uses: actions/checkout@v2
      with:
        repository: interactivereduction/k8s
        path: ~/k8s

    - name: Deploy the k8s local cluster version
      uses: arillso/action.playbook@master
      with:
        playbook: ~/k8s/ansible/deploy-dev-k8s-services.yml

    - name: Build new container and push it to cluster

    - name: Connect to kafka cluster and send message to "detected-runs" topic
      run: |
        

    - name: Wait and check to see if message is received as expected on "completed-runs" topic