---
on:
  push:

permissions:
  contents: write

jobs:
  formatting_and_linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Set up cache for Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          cd job_creator
          python -m pip install --upgrade pip
          python -m pip install .[formatting]

      - name: Run ruff formatting
        run: |
          ruff format .

      - name: Run ruff linting
        run: |
          ruff check --fix

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "black auto commit" || true
          git push

      - name: Run mypy
        run: |
          mypy --strict job_creator/jobcreator
          mypy --strict job_watcher/jobwatcher
